root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp/bin/web"
  cmd = "make build"
  delay = 1000
  exclude_dir = ["app/cmd/web/static", "tmp", "vendor", "testdata", "src/node_modules", "bin"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["app", "ui"]
  include_ext = ["go", "tpl", "tmpl", "html", "templ","css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

# Enable live-reloading on the browser.
[proxy]
  enabled = true
  proxy_port = 8090
  app_port = 8080

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
